"""create investigation and investigation_statuses tables with color on status

Revision ID: 22de8b2bf0f7
Revises: a0ca122a4851
Create Date: 2026-02-10 15:26:48.940378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22de8b2bf0f7'
down_revision: Union[str, Sequence[str], None] = 'a0ca122a4851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Goal: create the investigation_statuses and investigations tables (+ status/owner FKs). Input: none. Output: None."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_statuses',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_index(op.f('ix_investigation_statuses_name'), 'investigation_statuses', ['name'], unique=True)
    op.create_table('investigations',
    sa.Column('id_investigation', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_status'], ['investigation_statuses.id_status'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_investigation')
    )
    op.create_index(op.f('ix_investigations_id_status'), 'investigations', ['id_status'], unique=False)
    op.create_index(op.f('ix_investigations_owner_id'), 'investigations', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Goal: drop the investigations and investigation_statuses tables. Input: none. Output: None."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigations_owner_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_id_status'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_investigation_statuses_name'), table_name='investigation_statuses')
    op.drop_table('investigation_statuses')
    # ### end Alembic commands ###
