"""add_completed_at_to_tasks

Revision ID: 4691e8fda8e6
Revises: f1a2b3c4d5e6
Create Date: 2026-03-10 13:57:08.048421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4691e8fda8e6'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Goal: add the completed_at column to tasks. Input: none. Output: None."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Goal: drop the completed_at column from tasks. Input: none. Output: None."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_at')
    # ### end Alembic commands ###
