"""add investigation_collaborators table

Revision ID: 6285291b7871
Revises: 320b35c8a30e
Create Date: 2026-02-16 11:29:39.056450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6285291b7871'
down_revision: Union[str, Sequence[str], None] = '320b35c8a30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_collaborators',
    sa.Column('id_collaborator', sa.Integer(), nullable=False),
    sa.Column('id_investigation', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.Enum('manager', 'editeur', 'lecteur', name='permission_level_enum'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_investigation'], ['investigations.id_investigation'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id_user'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_collaborator'),
    sa.UniqueConstraint('id_investigation', 'id_user', name='uq_investigation_user')
    )
    op.create_index(op.f('ix_investigation_collaborators_id_investigation'), 'investigation_collaborators', ['id_investigation'], unique=False)
    op.create_index(op.f('ix_investigation_collaborators_id_user'), 'investigation_collaborators', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_collaborators_id_user'), table_name='investigation_collaborators')
    op.drop_index(op.f('ix_investigation_collaborators_id_investigation'), table_name='investigation_collaborators')
    op.drop_table('investigation_collaborators')
    # ### end Alembic commands ###
