"""add_categories_tables

Revision ID: d7194cc2068c
Revises: 6285291b7871
Create Date: 2026-02-17 12:07:05.029612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7194cc2068c'
down_revision: Union[str, Sequence[str], None] = '6285291b7871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Goal: create the categories and investigation_categories (link) tables. Input: none. Output: None."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('investigation_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_investigation', sa.Integer(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_category'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_investigation'], ['investigations.id_investigation'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_investigation', 'id_category', name='uq_investigation_category')
    )
    op.create_index(op.f('ix_investigation_categories_id_category'), 'investigation_categories', ['id_category'], unique=False)
    op.create_index(op.f('ix_investigation_categories_id_investigation'), 'investigation_categories', ['id_investigation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Goal: drop the investigation_categories and categories tables. Input: none. Output: None."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_categories_id_investigation'), table_name='investigation_categories')
    op.drop_index(op.f('ix_investigation_categories_id_category'), table_name='investigation_categories')
    op.drop_table('investigation_categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
